News_M/A_AD/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'A_AD'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('admin-dashboard/', views.admin_dashboard , name='admin-dashboard'),

    path('gestion-annonces/', views.gestion_annonces , name='gestion-annonces'),
    path('ajouter_annonce/', views.ajouter_annonce, name='ajouter-annonce'),
    path('modifier_annonce/<int:annonce_id>', views.modifier_annonce, name='modifier-_annonce'),
    path("supprimer-annonce/<int:id>/", views.supprimer_annonce, name="supprimer-annonce"),
    path('gestion-articles/', views.gestion_articles, name='gestion-articles'),
    path('modifier-article/<int:id>', views.modifier_article, name='modifier-article'),
    path("supprimer-article/<int:id>/", views.supprimer_article, name="supprimer-article"),
    path('ajouter-article/', views.ajouter_article, name='ajouter-article'),
    path('gestion-utilisateurs/', views.gestion_utilisateurs, name='gestion-utilisateurs'),
    path('gestion-commandes', views.liste_commandes, name='gestion-commandes'),
    path('gestion-utilisateurs/supprimer/<int:user_id>/', views.supprimer_utilisateur, name='supprimer_utilisateur'),
    path('ajouter_utilisateur/', views.ajouter_utilisateur, name='ajouter-utilisateur'),
    path('modifier-utilisateur/<int:user_id>', views.modifier_utilisateur, name='modifier-utilisateur'),
    path('contactez-nous/', views.contact_view, name='contactez-nous'),
    path('page-Annonces/',views.annonces_list,name='page-Annonces'),
    path('page-Articles/',views.article_list,name='page-Articles'),
    path('Article-detail/<int:article_id>/', views.article_detail, name='Article-detail'),
    path('page-contacts/', views.liste_contacts_admin, name='page-contacts'),
    path("categorie/<int:categorie_id>/", views.articles_par_categorie, name="articles_par_categorie"),
    path('commander-annonce/<int:annonce_id>', views.commander_annonce, name='commander-annonce'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

News_M/News_M/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from A_AD import views as a_ad_views
#  admin_super@gmail.com
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', a_ad_views.redirect_to_dashboard),
    path('auth/',include( 'authentification.urls')),
    path('a_ad/', include('A_AD.urls', namespace='A_AD')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

News_M/authentification/urls.py
from django.urls import path
from . import views

app_name = 'authentification'
urlpatterns = [
path('admin-login/', views.admin_login_view, name='admin-login'),
# path('Super-admin-login/', views.super_admin_login_view, name='Super-login'),
path("logout/", views.logout_view, name="logout"),
]

News_M/A_AD/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

from django.db import models


class Categorie(models.Model):
    nom = models.CharField(max_length=100)

    # إضافة حقل اللون (Bootstrap classes)
    color = models.CharField(
        max_length=20,
        choices=[
            ("primary", "Bleu"),
            ("success", "Vert"),
            ("danger", "Rouge"),
            ("warning", "Jaune"),
            ("info", "Cyan"),
            ("secondary", "Gris"),
        ],
        default="secondary"
    )

    def __str__(self):
        return self.nom


class Article(models.Model):
    titre = models.CharField(max_length=200)
    contenu = models.TextField()
    image = models.ImageField(upload_to='articles/', blank=True, null=True)
    video = models.FileField(upload_to='videos/', blank=True, null=True)
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    date_pub = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.titre

class Annonce(models.Model):
    titre = models.CharField(max_length=200)
    description = models.TextField()
    prix = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='annonces/', blank=True, null=True)

    date_pub = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titre

class ContactMessage(models.Model):

    nom = models.CharField(max_length=100)
    email = models.EmailField()
    sujet = models.CharField(max_length=200)
    message = models.TextField()
    date_envoi = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.nom} - {self.sujet}"



class ActionLog(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    action = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.action}"



class CommandeAnnonce(models.Model):
    nom = models.CharField(max_length=100)
    email = models.EmailField()
    annonce = models.ForeignKey(Annonce, on_delete=models.CASCADE)
    message = models.TextField(blank=True, null=True)
    date_commande = models.DateTimeField(auto_now_add=True)
    statut = models.CharField(
        max_length=20,
        choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')],
        default='en_attente'
    )

    def __str__(self):
        return f"Commande de {self.nom} - {self.annonce.titre}"

News_M/authentification/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    ROLE_CHOICES = [
        ('Super_admin', 'Super_admin'),
        ('admin', 'Admin'),
    ]
    role = models.CharField(max_length=50, choices=ROLE_CHOICES, default='admin')

    def __str__(self):
        return self.username

News_M/A_AD/views.py
from itertools import cycle
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.views import LogoutView
from django.views.decorators.cache import never_cache
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth.models import Permission
from .forms import CommanderAnnonceForm, AnnonceForm
from .models import Article, Annonce, ActionLog, ContactMessage, Categorie, CommandeAnnonce

User = get_user_model()


# ================== Decorators ==================

def super_admin_required(view_func):
    """تحقق من أن المستخدم Super_admin"""
    def wrapper(request, *args, **kwargs):
        if request.user.role != 'Super_admin':
            messages.error(request, "Vous n’avez pas la permission.")
            return redirect('authentification:admin-login')
        return view_func(request, *args, **kwargs)
    return wrapper


def permission_or_super_admin(permission_codename, login_url='/auth/admin-login/'):
    """تحقق من الصلاحية أو تجاوزها إذا كان Super_admin"""
    def decorator(view_func):
        def _wrapped_view(request, *args, **kwargs):
            if request.user.role == 'Super_admin' or request.user.has_perm(permission_codename):
                return view_func(request, *args, **kwargs)
            messages.error(request, "Vous n’avez pas la permission ")
            return redirect(request.META.get('HTTP_REFERER', '/'))
        return _wrapped_view
    return decorator


def filter_by_query(query, queryset, fields):
    """فلترة QuerySet حسب نص البحث"""
    if query:
        q_objects = Q()
        for field in fields:
            q_objects |= Q(**{f"{field}__icontains": query})
        queryset = queryset.filter(q_objects)
    return queryset


# ================== Home Page ==================

def home(request):
    query = request.GET.get('q')

    # Articles
    article_list = filter_by_query(query, Article.objects.all().order_by('-date_pub'), ["titre", "contenu"])
    article_paginator = Paginator(article_list, 5)
    page_articles = request.GET.get('article_page')
    articles = article_paginator.get_page(page_articles)

    # Annonces
    annonce_list = filter_by_query(query, Annonce.objects.all().order_by('-date_pub'), ["titre", "description"])
    annonce_paginator = Paginator(annonce_list, 3)
    page_annonces = request.GET.get('annonce_page')
    annonces = annonce_paginator.get_page(page_annonces)

    # Catégories avec couleurs
    categories = Categorie.objects.all()
    colors = ["primary", "success", "danger", "warning", "info"]
    categories_with_colors = [(cat, colors[i % len(colors)]) for i, cat in enumerate(categories)]

    return render(request, 'home.html', {
        'articles': articles,
        'annonces': annonces,
        'categories': categories_with_colors,
        'query': query,
    })


# ================== Dashboard ==================

@never_cache
@login_required(login_url='/auth/admin-login/')
def admin_dashboard(request):
    nb_articles = Article.objects.count()
    nb_annonces = Annonce.objects.count()
    nb_users = User.objects.count()
    last_actions = ActionLog.objects.order_by('-date')[:10]
    context = {
        'nb_articles': nb_articles,
        'nb_annonces': nb_annonces,
        'nb_users': nb_users,
        'last_actions': last_actions
    }
    return render(request, 'admin-dashboard.html', context)


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('authentification:admin-login')


# ================== Gestion Annonces ==================

@never_cache
@login_required
@permission_or_super_admin('A_AD.view_annonce')
def gestion_annonces(request):
    annonces = Annonce.objects.all()
    return render(request, 'gestion-annonces.html', {'annonces': annonces})


@never_cache
@login_required
@permission_or_super_admin('A_AD.add_annonce')
def ajouter_annonce(request):
    if request.method == 'POST':
        titre = request.POST.get('titre')
        description = request.POST.get('description')
        prix = request.POST.get('prix')
        image = request.FILES.get('image')
        annonce = Annonce.objects.create(titre=titre, description=description, prix=prix, image=image)
        ActionLog.objects.create(user=request.user, action=f"Ajout de l'annonce '{annonce.titre}'")
        messages.success(request, "Annonce ajoutée avec succès !")
        return redirect('A_AD:gestion-annonces')
    return render(request, 'ajouter_annonce.html')


@never_cache
@login_required
@permission_or_super_admin('A_AD.change_annonce')
def modifier_annonce(request, annonce_id):
    annonce = get_object_or_404(Annonce, id=annonce_id)
    if request.method == 'POST':
        form = AnnonceForm(request.POST, request.FILES, instance=annonce)
        if form.is_valid():
            form.save()
            ActionLog.objects.create(user=request.user, action=f"Modification de l'annonce '{annonce.titre}'")
            messages.success(request, "Annonce modifiée avec succès !")
            return redirect('A_AD:gestion-annonces')
    else:
        form = AnnonceForm(instance=annonce)
    return render(request, 'modifier_annonce.html', {'form': form})


@never_cache
@login_required
@permission_or_super_admin('A_AD.delete_annonce')
def supprimer_annonce(request, id):
    annonce = get_object_or_404(Annonce, id=id)
    titre = annonce.titre
    annonce.delete()
    ActionLog.objects.create(user=request.user, action=f"Suppression de l'annonce '{titre}'")
    messages.success(request, "Annonce supprimée avec succès !")
    return redirect("A_AD:gestion-annonces")


# ================== Gestion Articles ==================

@never_cache
@login_required
@permission_or_super_admin('A_AD.view_article')
def gestion_articles(request):
    articles = Article.objects.all()
    return render(request, 'gestion-articles.html', {'articles': articles})


@never_cache
@login_required
@permission_or_super_admin('A_AD.add_article')
def ajouter_article(request):
    if request.method == 'POST':
        titre = request.POST.get('titre')
        contenu = request.POST.get('description')
        image = request.FILES.get('image')
        video = request.FILES.get('video')
        article = Article.objects.create(titre=titre, contenu=contenu, image=image, video=video)
        ActionLog.objects.create(user=request.user, action=f"Ajout de l'article '{article.titre}'")
        messages.success(request, "Article ajouté avec succès !")
        return redirect('A_AD:gestion-articles')
    return render(request, 'ajouter_article.html')


@never_cache
@login_required
@permission_or_super_admin('A_AD.change_article')
def modifier_article(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method == 'POST':
        article.titre = request.POST.get("titre")
        article.contenu = request.POST.get("contenu")
        if request.FILES.get("image"):
            article.image = request.FILES["image"]
        if request.FILES.get("video"):
            article.video = request.FILES["video"]
        article.save()
        ActionLog.objects.create(user=request.user, action=f"Modification de l'article '{article.titre}'")
        messages.success(request, "Article modifié avec succès !")
        return redirect("A_AD:gestion-articles")
    return render(request, "modifier_article.html", {"article": article})


@never_cache
@login_required
@permission_or_super_admin('A_AD.delete_article')
def supprimer_article(request, id):
    article = get_object_or_404(Article, id=id)
    titre = article.titre
    article.delete()
    ActionLog.objects.create(user=request.user, action=f"Suppression de l'article '{titre}'")
    messages.success(request, "Article supprimé avec succès !")
    return redirect("A_AD:gestion-articles")


# ================== Gestion Utilisateurs ==================

@never_cache
@login_required
@permission_or_super_admin('auth.view_user')
def gestion_utilisateurs(request):
    utilisateurs = User.objects.all()
    return render(request, 'gestion-utilisateurs.html', {'utilisateurs': utilisateurs})


@never_cache
@login_required
@permission_or_super_admin('auth.add_user')
def ajouter_utilisateur(request):
    permissions = Permission.objects.all()
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        role = request.POST.get('role')
        perms_selected = request.POST.getlist('permissions')
        if User.objects.filter(username=username).exists():
            messages.error(request, "Nom d’utilisateur déjà utilisé !")
        else:
            utilisateur = User.objects.create_user(username=username, email=email, password=password, role=role)
            for perm_id in perms_selected:
                perm = Permission.objects.get(id=perm_id)
                utilisateur.user_permissions.add(perm)
            ActionLog.objects.create(user=request.user, action=f"Ajout de l'utilisateur '{username}'")
            messages.success(request, "Utilisateur ajouté avec succès !")
            return redirect('A_AD:gestion-utilisateurs')
    return render(request, 'ajouter_utilisateur.html', {'permissions': permissions})


@never_cache
@login_required
@permission_or_super_admin('auth.change_user')
def modifier_utilisateur(request, user_id):
    utilisateur = get_object_or_404(User, id=user_id)
    all_permissions = Permission.objects.all()
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        role = request.POST.get('role')
        password = request.POST.get('password')
        selected_perms = request.POST.getlist('permissions')

News_M/A_AD/templates/ajouter_annonce.html
<!DOCTYPE html>
<html lang="fr" dir="ltr">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Tableau de bord Administration</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body class="bg-white">

<!-- Barre de navigation Admin -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand d-flex align-items-center me-4 text-white" href="{% url 'A_AD:admin-dashboard' %}">
      <svg width="32" height="32" viewBox="0 0 24 24" fill="none" aria-label="Admin">
        <path d="M12 3l6 2v6c0 4.5-3.2 8.2-6 9-2.8-.8-6-4.5-6-9V5l6-2z" stroke="currentColor" stroke-width="1.6" />
        <circle cx="12" cy="12" r="2.2" stroke="currentColor" stroke-width="1.6"/>
        <path d="M12 8.8v-.9M12 16.1v-.9M15.2 12h.9M7.9 12h.9M14 10l.6-.6M9.4 14.6l.6-.6M14.6 14.6l-.6-.6M9.4 9.4l.6.6" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>
      </svg>
      <span class="fw-bold ms-2">Admin</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarAdmin"
      aria-controls="navbarAdmin" aria-expanded="false" aria-label="Menu de navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarAdmin">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><a class="nav-link " href="{% url 'A_AD:admin-dashboard' %}">Accueil</a></li>
        {% if perms.A_AD.view_annonce %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'A_AD:gestion-annonces' %}">Gestion des annonces</a>
            </li>
        {% endif %}

        {% if perms.A_AD.view_article %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'A_AD:gestion-articles' %}">Gestion des articles</a>
            </li>
        {% endif %}

        {% if perms.A_AD.view_user %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'A_AD:gestion-utilisateurs' %}">Gestion des utilisateurs</a>
            </li>
        {% endif %}

        {% if perms.A_AD.view_contactmessage %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'A_AD:page-contacts' %}">Contacts</a>
            </li>
        {% endif %}
      </ul>

      <!-- Bouton déconnexion -->
      <form method="POST" action="{% url 'authentification:logout' %}">
        {% csrf_token %}
        <button class="btn btn-outline-light">Déconnexion</button>
      </form>
    </div>
  </div>
</nav>








<div class="card shadow-sm p-4 mb-2">
    <h3 class="mb-3">Ajouter une nouvelle annonce</h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="mb-3">
            <label for="id_titre" class="form-label">Titre</label>
            <input type="text" name="titre" class="form-control" id="id_titre" required>
        </div>

        <div class="mb-3">
            <label for="id_description" class="form-label">Description</label>
            <textarea name="description" class="form-control" id="id_description" rows="4" required></textarea>
        </div>

        <div class="mb-3">
            <label for="id_prix" class="form-label">Prix (€)</label>
            <input type="number" name="prix" class="form-control" id="id_prix" step="0.01" required>
        </div>

        <div class="mb-3">
            <label for="id_image" class="form-label">Image</label>
            <input type="file" name="image" class="form-control" id="id_image">
        </div>

        <button type="submit" class="btn btn-success">Ajouter</button>
        <a href="{% url 'A_AD:gestion-annonces' %}" class="btn btn-secondary">Annuler</a>
    </form>
</div>


<footer class="bg-dark text-white text-center p-3 mt-4 ">
    <p class="mb-0">Tableau de bord Administration &copy; 2025</p>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

News_M/A_AD/templates/ajouter_article.html
{% load static %}
<!DOCTYPE html>
<html lang="fr" dir="ltr">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Tableau de bord Administration</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body class="bg-white">

<!-- Barre de navigation Admin -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand d-flex align-items-center me-4 text-white" href="{% url 'A_AD:admin-dashboard' %}">
      <svg width="32" height="32" viewBox="0 0 24 24" fill="none" aria-label="Admin">
        <path d="M12 3l6 2v6c0 4.5-3.2 8.2-6 9-2.8-.8-6-4.5-6-9V5l6-2z" stroke="currentColor" stroke-width="1.6" />
        <circle cx="12" cy="12" r="2.2" stroke="currentColor" stroke-width="1.6"/>
        <path d="M12 8.8v-.9M12 16.1v-.9M15.2 12h.9M7.9 12h.9M14 10l.6-.6M9.4 14.6l.6-.6M14.6 14.6l-.6-.6M9.4 9.4l.6.6" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>
      </svg>
      <span class="fw-bold ms-2">Admin</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarAdmin"
      aria-controls="navbarAdmin" aria-expanded="false" aria-label="Menu de navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarAdmin">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><a class="nav-link " href="{% url 'A_AD:admin-dashboard' %}">Accueil</a></li>
        {% if perms.A_AD.view_annonce %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'A_AD:gestion-annonces' %}">Gestion des annonces</a>
            </li>
        {% endif %}

        {% if perms.A_AD.view_article %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'A_AD:gestion-articles' %}">Gestion des articles</a>
            </li>
        {% endif %}

        {% if perms.auth.view_user %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'A_AD:gestion-utilisateurs' %}">Gestion des utilisateurs</a>
            </li>
        {% endif %}

        {% if perms.A_AD.view_contactmessage %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'A_AD:page-contacts' %}">Contacts</a>
            </li>
        {% endif %}
      </ul>

      <!-- Bouton déconnexion -->
      <form method="POST" action="{% url 'authentification:logout' %}">
        {% csrf_token %}
        <button class="btn btn-outline-light">Déconnexion</button>
      </form>
    </div>
  </div>
</nav>





<div class="card shadow-sm p-4 mb-5">
    <h3 class="mb-3">Ajouter une nouvelle Article</h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="mb-3">
            <label for="id_titre" class="form-label">Titre</label>
            <input type="text" name="titre" class="form-control" id="id_titre" required>
        </div>

        <div class="mb-3">
            <label for="id_description" class="form-label">Contenu</label>
            <textarea name="description" class="form-control" id="id_description" rows="3" required></textarea>
        </div>

       <div class="mb-3">
            <label for="id_image" class="form-label">Image</label>
            <input type="file" name="image" class="form-control" id="id_image">
       </div>

        <div class="mb-3">
            <label for="id_video" class="form-label">video</label>
            <input type="file" name="video" class="form-control" id="id_video">
        </div>
        <div class="mb-3">
            <label for="id_categorie">Catégorie</label>
            <select name="categorie" id="id_categorie" class="form-select">
                {% for cat in categories %}
                    <option value="{{ cat.id }}">{{ cat.nom }}</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" class="btn btn-success">Ajouter</button>
        <a href="{% url 'A_AD:gestion-articles' %}" class="btn btn-secondary">Annuler</a>
    </form>
</div>


<footer class="bg-dark text-white text-center p-3 mt-4  ">
    <p class="mb-0">Tableau de bord Administration &copy; 2025</p>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

News_M/A_AD/templates/articles_par_categorie.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}Tableau de bord Administration{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
      /* Fixe le footer en bas */
      html, body {
        height: 100%;
      }
      body {
        display: flex;
        flex-direction: column;
      }
      main {
        flex: 1;
      }
    </style>
</head>
<body>

<!-- Barre de navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid justify-content-center">

    <!-- Logo -->
    <a class="navbar-brand d-flex align-items-center me-4" href="{% url 'A_AD:home' %}">
      <img src="https://img.icons8.com/color/96/news.png"
           alt="logo" width="40" height="40" class="rounded me-2"/>
      <span class="fw-bold text-white">NEWS</span>
    </a>

    <!-- Toggle button for mobile -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarAdmin">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar links centered -->
    <div class="collapse navbar-collapse justify-content-center" id="navbarAdmin">
      <ul class="navbar-nav mb-2 mb-lg-0 d-flex gap-3">
      <li class="nav-item"><a class="nav-link" href="{% url 'A_AD:home' %}">Accueil</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'A_AD:page-Articles'%}">Actualités</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'A_AD:page-Annonces' %}">Annonces</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'A_AD:contactez-nous' %}">Contactez-nous</a></li>
    </ul>

    </div>
  </div>
</nav>





<div class="container mt-4 " >

    <div class="text-center mb-4">
        <h2 class="fw-bold text-white py-3 px-4 rounded shadow bg-{{ categorie.color }}">
            📚 Articles - {{ categorie.nom }}
        </h2>
    </div>

    <hr>

    {% if articles %}
        <div class="row">
            {% for article in articles %}
                <div class="col-md-6 mb-3">
                    <div class="card shadow-sm">
                        <div class="card-body ">
                            {% if article.image %}
                                <img src="{{ article.image.url }}" alt="Image de l'article" style="width:100%; height: 300px">
                            {% endif %}
                            <h5 class="card-title">{{ article.titre }}</h5>
                            <p class="card-text">{{ article.contenu|truncatewords:30 }}</p>
                            <small class="text-muted">{{ article.date_pub|date:"d/m/Y H:i" }}</small>
                        <div class="d-flex align-items-center gap-2">
                            <p class="badge bg-{{article.categorie.color}} mb-0 d-flex align-items-center justify-content-center" style="height: 30px;">{{ article.categorie.nom }}</p>
                            <a href="{% url 'A_AD:Article-detail' article.id %}" target="_blank" class="btn btn-primary d-flex align-items-center justify-content-center" style="height: 30px; line-height: 30px;">Lire plus</a>
                        </div>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    {% else %}
        <p>Aucun article disponible pour cette catégorie.</p>
    {% endif %}
</div>


<footer class="bg-dark text-white text-center p-3">
    <p>Tous droits réservés &copy; 2025</p>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>